### ISSUE TITLE
NoClassDefFoundError: lach_01298/qmd/crafttweaker/QMDCTRegistration$2

### ISSUE THREAD

**Issue by baifeiajdj** [Lach01298/QMD#102]
environment：cleamroom15.24.0.3038
[crash-2024-05-07_12.05.53-client.txt](https://github.com/Lach01298/QMD/files/15229309/crash-2024-05-07_12.05.53-client.txt)
[crash-2024-05-07_12.05.54-client.txt](https://github.com/Lach01298/QMD/files/15229310/crash-2024-05-07_12.05.54-client.txt)

**Comment by Lach01298** [comment]
You are using a version of nuclearcraft overhaul that QMD isn't updated to work on. QMD 1.32 only works on NCO 2o.6.2

**Comment by I2pRandom** [comment]
I just got the same issue, I confirmed I'm on NCO version 2o.6.2. 
[latest.log](https://github.com/user-attachments/files/16102449/latest.log)
[debug.log](https://github.com/user-attachments/files/16102457/debug.log)
[crash-2024-07-04_14.49.40-client.txt](https://github.com/user-attachments/files/16102459/crash-2024-07-04_14.49.40-client.txt)

**Comment by Lach01298** [comment]
Your using the wrong NCO version for QMD 1.4 You need NCO 2o.7.7
