### ISSUE TITLE
QMD Crashing on startup with error java.lang.NoSuchMethodError: nc.util.Lang.localise(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by MyUsernameisAstro** [Lach01298/QMD#103]
https://mclo.gs/SC3VzCK

No other mods active outside of nuclearcraft and QMD

**Comment by Lach01298** [comment]
You are using a version of nuclearcraft overhaul that QMD isn't updated to work on. QMD 1.31 only works on NCO 2o.6.2
