### ISSUE TITLE
Crash with latest NCO

### ISSUE THREAD

**Issue by mczph** [Lach01298/QMD#104]
NCO made huge changes in 2o.7.x,which broke compatibility with QMD
Crash report:https://mclo.gs/Q2uqRx0
Also when you have Crafttweaker:https://mclo.gs/87i8XJy

**Comment by Lach01298** [comment]
You are using a version of nuclearcraft overhaul that QMD isn't updated to work on. QMD 1.3.2 only works on NCO 2o.6.2
