### ISSUE TITLE
Nucleosynthesis chamber buffer never empties

### ISSUE THREAD

**Issue by Tomoyukiryu** [Lach01298/QMD#105]
I'm using Nucleosynthesis chamber to do muon assisted fusion using liquid deuterium and liquid hydrogen from Mekanism. There is no flow  of liquid into the chamber and even when I destroy the pipes connecting to the chamber the buffers are still full

**Comment by Tomoyukiryu** [comment]
Update; the bufferes emptied after I  destroyed pipes supplying the fuels and exited and joined the world

**Comment by Lach01298** [comment]
I'm not entirely sure what your problem is. Is it that you can't fill the tanks or they don't empty? You can empty each tank by shift clicking it in the gui.

**Comment by Tomoyukiryu** [comment]
The tanks once filled with liquid hydrogen and liquid deuterium from Mekanism never get empty  unless I purge the liquids manually. The recipe doesn't use up the fluids at all until I either purge the tanks or reload the world

**Comment by Lach01298** [comment]
Are you using the right energy for the muons?

**Comment by Tomoyukiryu** [comment]
I'm decelerating muons to O keV and I know recipe is being done cause it is indicated in GUI, helium-3 comes out and hot mercury goes into a turbine. The only thing that's not changing is amount of liquid deuterium and liquid hydrogen

**Comment by Lach01298** [comment]
Hmm I think this is just a GUI bug. What version of QMD are you using?

**Comment by Lach01298** [comment]
fixed in 1.3.4
