### ISSUE TITLE
Server crashing when completing Linear accelerator with Accelerator Ion Collector

### ISSUE THREAD

**Issue by Mooselogger** [Lach01298/QMD#106]
[Server dump logs](https://mclo.gs/y3mJzCS)

I've tried building a linear accelerator as described in the wiki  (https://github.com/Lach01298/QMD/wiki/Linear-Accelerators), but everytime it completes my server crashes. 

Issue reproducable? Yes. I've managed to break my server three times (fixed by rolling back to previous backup) by almost completing (one missing block) the linear accelerator and having the last block be a Accelerator Ion Collector

**Comment by Mooselogger** [comment]
Here is a picture of the setup. I have done this the same way three times in a row and gotten the same dump every time. The final block to the left of the redstone port has been an Accelerator Ion Collector, which I believe causes render issues when the machine is "final".
![2024-05-28_22 45 41](https://github.com/Lach01298/QMD/assets/19285769/0ef87fed-7d9f-429a-8c1b-f37b0c3a45de)

To be sure I can complete the machine, here is a picture of the complete build:
![2024-05-28_22 48 47](https://github.com/Lach01298/QMD/assets/19285769/b3eb7444-1a16-4ee7-96f1-5d7d4be7fcd6)

I am playing on Enigmatica 2: Expert - Extended 1.38.1
Minecraft version: 1.12.2
Forge version: 14.23.5.2860
QMD version: 1.3.3-1.12.2
![bilde](https://github.com/Lach01298/QMD/assets/19285769/5e0c8e8e-ffdd-4a75-b0a5-bdc76fd26b8e)

**Comment by Lach01298** [comment]
fixed in 1.3.5
