### ISSUE TITLE
Strange electromagnetic cell behaviors

### ISSUE THREAD

**Issue by 238-Pu** [Lach01298/QMD#34]
Empty cells cannot be charged (in fact the energetic infuser from Thermal Expansion won't even accept them in the first place) and filled antimatter cells spawn with zero charge and will not explode. As far as I know there is no odd NBT data on it, and nothing shows up in the logs.

**Comment by christheboss894** [comment]
to add on to this, if you attempt to shift click the cell into the energetic infuser, it treats it as if it was a power source, and puts it into the power input

**Comment by Lach01298** [comment]
solved in 0.12
