### ISSUE TITLE
Lag spikes?

### ISSUE THREAD

**Issue by Elfinslayer** [Lach01298/QMD#35]
Currently, on FTB University we have a server of around 20 members and started to get random lag spikes. Investigating brought me to find this:

![image](https://user-images.githubusercontent.com/32952542/99135482-e2977700-25ce-11eb-961e-19f2b10827b1.png)

that is the average over 30s, it spikes as high as 5,000,000 us/t (5s) and is very noticeable. Thoughts or suggestions on a fix?

**Comment by Lach01298** [comment]
what version of QMD are you using? 
0.9.4 should have fixed this

**Comment by Elfinslayer** [comment]
It appears that FTB University uses QMD-0.10.1-1.12.2

**Comment by Poisonsting** [comment]
Happening with QMD-0.10.1-1.12.2 to me as well.
![QMD Server Killer](https://user-images.githubusercontent.com/3866157/99162508-c291b180-26bb-11eb-9870-7c0ec2f5ea5c.PNG)

**Comment by Elfinslayer** [comment]
Any updates on this? I ended up having to disable the QMD mod completely, which has broken nuclear craft on my server.

**Comment by Lach01298** [comment]
what is the config for item_ticker_chunks_per_tick?

**Comment by Lach01298** [comment]
It seems FTB uni uses the default which should be fine and not cause much lag at all. Try setting item_ticker_chunks_per_tick to 0 to see if that helps.

**Comment by Poisonsting** [comment]
In my case setting item_ticker_chunks_per_tick to 0 worked, anything higher causes the bug.

**Comment by Lach01298** [comment]
hmm I'll have to look into it

**Comment by Lach01298** [comment]
Solved in 1.12
