### ISSUE TITLE
Null Pointer Exception On Running Recipes Without Item Products

### ISSUE THREAD

**Issue by practicalphilosophie** [Lach01298/QMD#40]
A crash when running a certain target chamber recipe has been encountered and successfully reproduced on a fresh world. The target chamber recipe of deuterons impacting Li-7, which outputs only particles and not item products, will place the world into a state that consistently causes crashes when loaded once the recipe is finished and the Li-7 is consumed. 

Crash log: [https://pastebin.com/4PmumMqd](url)

**Comment by Lach01298** [comment]
fixed in 0.12.1
