### ISSUE TITLE
Gregicality's Liquid Helium can't work in accelerators

### ISSUE THREAD

**Issue by TheRealKamisama** [Lach01298/QMD#41]
version:  
`Gregicality-1.12.2-0.21.1.jar`  
`QMD-0.11.0-1.12.2.jar`   
`Minecraft-1.12.2`  
`Forge-14.23.5.2854`  
I tried to build a Linear Accelerator in single player, and I pumped liquid helium in, it just won't work and I checked the JEI recipes, it shows this.  
![liquid helium](https://user-images.githubusercontent.com/35005476/104845348-e964a200-590f-11eb-9e4f-eaaad57a2cda.png)
![all coolant](https://user-images.githubusercontent.com/35005476/104845354-eff31980-590f-11eb-8222-fd6cafeaf7e4.png)
The temperature of the Gregicality Liquid Helium is 300k, it supposed to be 4k in QMD refer to the wiki.  
Nuclearcraft's Liquid Helium is missing and all the related recipe's Liquid Helium was replaced with Gregicality's.  
I‘m not sure this is QMD's problem or GTCE's, because I refered to GTCE's code and found this:  
`https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/unification/material/Materials.java#L64`

**Comment by TheRealKamisama** [comment]
https://github.com/Gregicality/gregicality/pull/322  
My friend's PR trying to fix this issue.  
Seems like it's Gregicality

**Comment by Lach01298** [comment]
Seems really to be Gregicality issue since it's liquid helium temperature is wrong helium.
