### ISSUE TITLE
Can't charge the HEV suit

### ISSUE THREAD

**Issue by Hogan-Dazs** [Lach01298/QMD#50]
I've tried both the Immersive Engineering charging station and a charger from Chargers, which both use FE, as well as the Energetic Infuser from Thermal but can't charge the HEV. What is the recommended way to charge it?

**Comment by Lach01298** [comment]
This is know and is a nuclearcraft bug. But as it currently is you don't require power for the HEV suit yet.

**Comment by Lach01298** [comment]
fixed in 0.13.4 forgot to close issue
