### ISSUE TITLE
Crash Caused by java.lang.NoClassDefFoundError: nc/network/multiblock/MultiblockUpdatePacket

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [Lach01298/QMD#54]
[minecraft-exported-logs-2021-04-25T10-54-24.log.txt](https://github.com/Lach01298/QMD/files/6371665/minecraft-exported-logs-2021-04-25T10-54-24.log.txt)

**Comment by Lach01298** [comment]
You are using the wrong NC version for that QMD version . You need 2o.5.x for 0.13.3

**Comment by WuzgXY-GitHub** [comment]
> You are using the wrong NC version for that QMD version . You need 2o.5.x for 0.13.3

Ok, sorry for bothering
