### ISSUE TITLE
Spew of errors with particle decelerator

### ISSUE THREAD

**Issue by Jimmy469** [Lach01298/QMD#56]
As seen here: https://youtu.be/vFdj829eOdA?t=2145

Accompanying crash report: https://paste.dimdev.org/evumizotis.mccrash (just one of many, but they all look similar)

Let me know if additional information is needed (decelerator design, etc.)

**Comment by Lach01298** [comment]
I think this and the other bug are caused by the multiblock not forgetting its particle beams after being broken

**Comment by Lach01298** [comment]
Fixed in 1.0.0-beta
