### ISSUE TITLE
Converting a synchrotron to a decelerator retains 5MeV minimum input energy

### ISSUE THREAD

**Issue by Jimmy469** [Lach01298/QMD#57]
In the process of building a decelerator, I accidentally placed a synchrotron controller instead. When swapping back to the decelerator controller, the multiblock retained the 5MeV minimum input energy requirement. Breaking and replacing the controller didn't help, since the error persisted.

Ultimately I tore down the entire thing and rebuilt the exact same structure, just with the right controller from the beginning. I believe decelerators aren't intended to have the input energy minimum, although I could be wrong.

**Comment by Lach01298** [comment]
Fixed in 1.0.0-beta
