### ISSUE TITLE
Incorrect recipe with electrolysing salt

### ISSUE THREAD

**Issue by player19375** [Lach01298/QMD#59]
<img width="435" alt="Screenshot 2021-08-02 at 00 56 05" src="https://user-images.githubusercontent.com/83454653/127779530-1ec21dc8-0190-4b17-8d82-95b6716925c3.png">

The recipe for electrolysing salt gives 2 buckets of hydrogen and 1 bucket of chlorine per bucket of salt solution. It should give 2 buckets of sodium hydroxide instead of hydrogen. (Assuming that capturing the hydrogen from that process is not easy to do) 

Edit: It looks like it's an issue in 
https://github.com/Lach01298/QMD/blob/887ff6a94fddee6a76cc6e38108b1331047f6e41/src/main/java/lach_01298/qmd/recipes/QMDRecipes.java#L235 ,
where hydrogen is mentioned instead of sodium hydroxide.

**Comment by Lach01298** [comment]
Fixed recipe for next release
