### ISSUE TITLE
Target chamber doesn't detect recipe when they last only 1 tick (sometimes)

### ISSUE THREAD

**Issue by kubulll** [Lach01298/QMD#66]
The bad thing about trying to replicate it is that you can't just by putting target chamber + very high pu/t creative particle source cause that actually seems to work. The way i got this is making a long chain of accelerators, synchotrons, decay and target chambers and the recipes seem to stop around the middle of it (probably when it gets to 1 recipe/t). Only reason i can see this happening is because recipe doesn't get recognised and doesn't produce particles further
![image](https://user-images.githubusercontent.com/43418203/131217583-dc18a71e-d7c5-487b-abbd-e0aae831b14d.png)
![image](https://user-images.githubusercontent.com/43418203/131217592-42af333e-278d-42d5-9590-3e7ead8aa9ae.png)
The images represent the recipe it screws on and the setup (recipe uses U-238)

**Comment by Lach01298** [comment]
Can you post the world?

**Comment by kubulll** [comment]
[power positive R-process.zip](https://github.com/Lach01298/QMD/files/7072539/power.positive.R-process.zip)
i think you only need QMD + thermal mods but i would also add trinity

**Comment by kubulll** [comment]
i can also VC with you and show what i'm doing exactly
