### ISSUE TITLE
Anti-Matter Cells Crash Server (Magma Server)

### ISSUE THREAD

**Issue by cheesebobi** [Lach01298/QMD#72]
Hello! Im having an issue where dropping the cells from QMD instantly crashes the server. I'm running a Magma server so I'm not sure if it's a magma specific issue or if it occurs on forge servers too. I was wondering whether it was a visual issue that crashes the server but since it seems to use a similar animation to that of the trinity explosions I think it has to be some code issue as those work without any issues.

[crash-2022-01-17_17.16.28-server.txt](https://github.com/Lach01298/QMD/files/7887897/crash-2022-01-17_17.16.28-server.txt)

Thanks in advance! Love your work!

**Comment by Lach01298** [comment]
That my bad I use a client side only method there

**Comment by Lach01298** [comment]
Fixed in 1.1-beta4
