### ISSUE TITLE
Water Accelerator Cooler consumes fluid containers on crafting.

### ISSUE THREAD

**Issue by CassandraRC7** [Lach01298/QMD#73]
Crafting a Water Accelerator Cooler causes the fluid container used to craft it to be consumed along with the fluid it contains. Tested both in an ME terminal and in a vanilla crafting table with both a watering can and reservoir.

Expected: The reservoir would not be consumed, and would only lose 1000 mB of water
Actual: The reservoir is consumed

To replicate:
1. Have Thermal Expansion and QMD installed
2. Be in survival mode
3. Craft together an empty cooler along with a reservoir full of water to make a Water Accelerator Cooler

**Comment by Lach01298** [comment]
Weird I tested it in a crafting table and it works as expected.

**Comment by Lach01298** [comment]
Interesting it works with 1 bucket in the reservoir but not multiple. I don't actually add the recipes so it a thermal bug not a QMD bug. The normal bucket recipe is what I add and it works fine.

**Comment by CassandraRC7** [comment]
It works for other recipes that use water buckets like that, such as the
water fission heat sink.
