### ISSUE TITLE
Crash with NCo version 2o.6.0

### ISSUE THREAD

**Issue by magcicada** [Lach01298/QMD#74]
Just crash with NCo version 2o.6.0 when placing the machine blocks, it can get different crash reports with this same error:
`java.lang.NoSuchMethodError: nc.tile.processor.TileItemFluidProcessor.<init>(Ljava/lang/String;IIIILjava/util/List;Lit/unimi/dsi/fastutil/ints/IntList;Ljava/util/List;Ljava/util/List;IIZLnc/recipe/BasicRecipeHandler;II)V`

**Comment by Lach01298** [comment]
I need to update the mod to work with 2o.6.0

**Comment by Faolon12** [comment]
I get this same issue, is there a estimated time on an update?
