### ISSUE TITLE
Issues with Irradiator in latest NCO version

### ISSUE THREAD

**Issue by whatsapp2** [Lach01298/QMD#75]
I've been having issues with the irradiator, it crashes the server immediately after placing the block
Here's the crash report
[crash-2022-04-11_20.33.43-server.txt](https://github.com/Lach01298/QMD/files/8467600/crash-2022-04-11_20.33.43-server.txt)

**Comment by Lach01298** [comment]
Haven't updated mod to that NCO version yet
