### ISSUE TITLE
New version release on CurseForge request

### ISSUE THREAD

**Issue by GBLodb** [Lach01298/QMD#79]
Now since the compatibility with NCO6.0+ has been completed, can the latest version be released on CurseForge?

**Comment by Lach01298** [comment]
I was sort of waiting for the next version because I'm pretty sure there are some bugs in 2o.6. Also I was wanting the next update to be a full release of 1.1. I haven't really been working on it because I've been busy lately.

**Comment by mczph** [comment]
NCO2o.6.2 is recently released, does this have an impact on the QMD1.1 update?

**Comment by Lach01298** [comment]
Yes it does. I am working on 1.1 currently.
