### ISSUE TITLE
Energy overflow in large accelerators

### ISSUE THREAD

**Issue by pablocnvs** [Lach01298/QMD#8]
When constructing large accelerators, such as the one in the example, particle that have more than 2.1TeV are not allowed. The message about particle energy being too low leads me to the assumption that the energy has exceded the 32-bit integer limit, and is thus a negative number.
I have basic knowlegde about the types of numbers that can be inserted into java and are suported by Minecraft, but i assume that it can be changed to a 64-bit integer, which, in the case of qmd energy, would mean an energy of about 10 ZeV, a value stupidly large.

![2020-05-03_10 33 45](https://user-images.githubusercontent.com/64352555/80909588-b058b300-8d29-11ea-87ff-e0ed3a667fef.png)

In the image, the input is a proton from a 5MeV linear accelerator with a focus of 5.35

The accelerator itself works, as when i try with alpha particles coming from a target chamber with 5.125 MeV and a focus of 1.2

![2020-05-03_11 02 48](https://user-images.githubusercontent.com/64352555/80910188-121b1c00-8d2e-11ea-9cf1-9385c278f40c.png)

**Comment by pablocnvs** [comment]
I have looked up at the code, with the most basic intuiton, and I see particle mean energy is treated as an 64-bit value, so I don't know what is the issue.

**Comment by Lach01298** [comment]
Can you show a picture of the set up and of the linear accelerators GUI?

**Comment by pablocnvs** [comment]
Here are the screenshots for the entire set-up:

The alpha particle source (collision of p with Be)

 
![2020-05-04_14 02 25](https://user-images.githubusercontent.com/64352555/80964292-e3c23d00-8e10-11ea-8973-b1072f8061b0.png)
![2020-05-04_14 02 27](https://user-images.githubusercontent.com/64352555/80964295-e45ad380-8e10-11ea-8981-fa8e8780f91c.png)
![2020-05-04_14 02 39](https://user-images.githubusercontent.com/64352555/80964298-e4f36a00-8e10-11ea-8528-fdb4af46f2c9.png)
![2020-05-04_14 02 41](https://user-images.githubusercontent.com/64352555/80964299-e4f36a00-8e10-11ea-90ad-65feaa76ee33.png)
![2020-05-04_14 02 44](https://user-images.githubusercontent.com/64352555/80964302-e58c0080-8e10-11ea-9592-4a80e3effe38.png)
![2020-05-04_14 02 56](https://user-images.githubusercontent.com/64352555/80964304-e6249700-8e10-11ea-8de5-bfcb761d8fc2.png)
![2020-05-04_14 02 58](https://user-images.githubusercontent.com/64352555/80964305-e6249700-8e10-11ea-9e4e-63dbb895ab94.png)
![2020-05-04_14 03 10](https://user-images.githubusercontent.com/64352555/80964306-e6bd2d80-8e10-11ea-80e1-6451d0843c2f.png)
![2020-05-04_14 04 34](https://user-images.githubusercontent.com/64352555/80964483-3c91d580-8e11-11ea-8c65-4e1b928fe952.png)

The proton source

![2020-05-04_14 04 08](https://user-images.githubusercontent.com/64352555/80964338-f5a3e000-8e10-11ea-8d49-786783a6ff7a.png)
![2020-05-04_14 04 10](https://user-images.githubusercontent.com/64352555/80964339-f63c7680-8e10-11ea-91fd-4eab94dbcdad.png)
![2020-05-04_14 04 41](https://user-images.githubusercontent.com/64352555/80964504-46b3d400-8e11-11ea-91b1-806b26f52df3.png)

The set-up as a whole

![2020-05-04_14 05 35](https://user-images.githubusercontent.com/64352555/80964389-0f452780-8e11-11ea-8c82-270b6d5ae027.png)

I have included all the GUIs, as well as the information about each particle at each stage

**Comment by pablocnvs** [comment]
I have redone the math, and it turns out that the energy of the proton should actually be lower

¡

**Comment by Lach01298** [comment]
Hmmm weird. Can I have the world to do some testing?

**Comment by pablocnvs** [comment]
Sure, I send you the world. I will also send you the list of mods I have used, which I have reduced to make it easier for you to test. Though I have improved the accelerator

[NC overhaul test.zip](https://github.com/Lach01298/QMD/files/4591390/NC.overhaul.test.zip)
[Mod List.txt](https://github.com/Lach01298/QMD/files/4591443/Mod.List.txt)

**Comment by pablocnvs** [comment]
``

**Comment by pablocnvs** [comment]
I have no idea what I did, because i have tried to redo the accelerator using the screenshots you gave me, but i cannot seem to reproduce myself. With higher values, with the accelerator I provided you, or lower, with a downgrade I tried to do to, it works. I will try to reproduce the values and check again, but it is really weird.

**Comment by pablocnvs** [comment]
I think I can close this issue, as I reproduced the exact same accelerator, but I keep failing at reproducing the bug. Though, to be honest, seeing how powerful can this accelerators get, unless higher energies are required than a few TeV, I might see fitting a restriction on the minimum energy the particles must have to enter the syncroton, like, a 1/500 the maximum energy. Though powering just one of these behemoths is a challenge in its own right.

**Comment by Lach01298** [comment]
Yeah I was thinking of having the minimum energy be proportional to its energy. Haven't done it for some reasons might inn the future. Well I suppose I close this issue for now.
