### ISSUE TITLE
Ticking entity crash upon firing an antimatter projectile

### ISSUE THREAD

**Issue by Brown-bricks** [Lach01298/QMD#89]
Firing an antimatter projectile causes the world to crash due to the game attempting to add radiation to the projectile entity.

Tested in a fairly heavy and eclectic modpack.
[crash-2023-04-07_23.21.40-server.txt](https://github.com/Lach01298/QMD/files/11182615/crash-2023-04-07_23.21.40-server.txt)

**Comment by Lach01298** [comment]
Is nuclearcraft radiation disabled?
