### ISSUE TITLE
Request for Deuterium Recipe Mass Spectrometer

### ISSUE THREAD

**Issue by Thalzamar** [Lach01298/QMD#91]
please add a water -> oxygen , hydrogen , deuterium recipe to the mass spectrometer 
can be in the realistic relation of 
3200mb water -> 1600mb oxygen , 3199mb water , 1mb deuterium

**Comment by Lach01298** [comment]
Sure

**Comment by 238-Pu** [comment]
Wouldn't this result in a hydrogen -> deuterium converter as you could just take the hydrogen and oxygen and recombine them into water and send the water back through?

**Comment by Lach01298** [comment]
I thought about it and yes this would convert hydrogen to deuterium but it really doesn't matter because by default water is infinite and is already an infinite source of deuterium.
