### ISSUE TITLE
CTD with Mass Spectrometer

### ISSUE THREAD

**Issue by Thalzamar** [Lach01298/QMD#92]
recipe for pure boron crystals registers fine without an error in the crafttweaker log
but as soon i but one in the mass spectrometer it ctd 
might be because i have a mass spectrometer with multiple magnets+beamlines for x4 speed 
i have placed 4 itemducts on the first beamline and 4 fluiducts on the third
crash log:
[crash-2023-11-12_18.19.21-server.txt](https://github.com/Lach01298/QMD/files/13328674/crash-2023-11-12_18.19.21-server.txt)
addon:
[AOP.zip](https://github.com/Lach01298/QMD/files/13328676/AOP.zip)
Recipe:
![grafik](https://github.com/Lach01298/QMD/assets/48890032/98962103-f365-44d8-bcf6-3dc5d4af6b39)
Mass Spectro:
![grafik](https://github.com/Lach01298/QMD/assets/48890032/57168599-dff4-42cd-a319-90a2963feff6)

**Comment by Thalzamar** [comment]
Forgot to mention:
it crashes when the recipe is done

**Comment by Thalzamar** [comment]
actually it also ctd with the normal boron recipe

**Comment by Lach01298** [comment]
Should be fixed for 1.3
