### ISSUE TITLE
Crash if ion source fluid consumption is less than 1 mB/t

### ISSUE THREAD

**Issue by 238-Pu** [Lach01298/QMD#93]
If the fluid consumption rate of an accelerator ion source is less than 1 mB/t due to altered mole and/or ion source particle output configs, the game will crash the instant the accelerator is activated.
[crash-2023-11-23_11.54.08-server.txt](https://github.com/Lach01298/QMD/files/13453394/crash-2023-11-23_11.54.08-server.txt)

**Comment by Lach01298** [comment]
I've decided to remove those configs and add a general particle recipe speed config that is easier to control. Also making the ion source use 1mb/t minimum to stop crashes. If people really want to change the amount of particles recipes use drastically from default QMD's balance then they will have to do it to recipes individually with craft tweaker and face the consequences.
