### ISSUE TITLE
[Feature Request] Add option to not register vanilla-like tools

### ISSUE THREAD

**Issue by Krutoy242** [Lach01298/QMD#96]
Since in `E2E-E` Tinker's Construct is core equipment mod, i removing all vanilla-like tools from game. It would be cool if they would not even register, by disabling them in config.

Right now im using CT code, that remove and hide those items, but they still persist in registry and take CPU time to create and them remove their recipes.

![image](https://github.com/Lach01298/QMD/assets/936618/dd3f71fa-d1d5-4ab5-a0b2-5a710893d5ee)

```ts
// Remove tools
utils.rh(<qmd:sword_tungsten_carbide>);
utils.rh(<qmd:pickaxe_tungsten_carbide>);
utils.rh(<qmd:shovel_tungsten_carbide>);
utils.rh(<qmd:axe_tungsten_carbide>);
utils.rh(<qmd:hoe_tungsten_carbide>);
```

**Comment by Lach01298** [comment]
I argue that the performance impact is negligible for 5 items and that you can't remove vanilla tools from the registry either unless your using some core mod. 

Even so I don't see a problem adding the config. It not a priority though so might not be added for some time as I'm not planning updating QMD for a bit.

**Comment by Lach01298** [comment]
It has been added to 1.3.1 whenever that comes out
