### ISSUE TITLE
Overcooling gives bonus in Nucleosynthesis Chamber

### ISSUE THREAD

**Issue by Zaobingyu** [Lach01298/QMD#98]
As the title, there's something wrong in the Nucleosynthesis Chamber. Overcooling actually give output bonus in it. It seems that output=(output when the efficiency is 100%)/efficiency.
![image](https://github.com/Lach01298/QMD/assets/87657201/17900328-f033-4975-b22f-751ae2ae5553)
![image](https://github.com/Lach01298/QMD/assets/87657201/d865ee7c-b651-4267-afc1-ab08b7ce07cf)
![image](https://github.com/Lach01298/QMD/assets/87657201/61fea943-3a25-44ea-b329-7260bcc93452)
![image](https://github.com/Lach01298/QMD/assets/87657201/b5da9cbe-39d7-4711-a6ed-139e50925cec)

**Comment by Lach01298** [comment]
Fixed in 1.3.1
