### ISSUE TITLE
Can increase the internal energy cache of the ore leacher？

### ISSUE THREAD

**Issue by 13584452567** [Lach01298/QMD#99]
Due to insufficient internal energy cache, the ore leacher refused to work after inserting a few energy upgrades.
Can u increase the internal energy cache of the ore leacher？
Thank you very much！

**Comment by Lach01298** [comment]
Need more detail as I can not reproduce. I can put a full stack of speed upgrades and the ore leacher will run just fine.

Are you using a custom recipe or configs?

**Comment by Lach01298** [comment]
No response and not enough information on issue so closing.
